generation:
  max_tokens: 8192
  temperature: 1.0
ollama:
  base_url: http://localhost:11434
  embedding_model: nomic-embed-text
  model: deepseek-r1:latest
openai:
  api_key: sk-proj-IL_mlxxxA
  base_url: https://api.openai.com/v1
  model: gpt-4o-mini
rag:
  chunk_overlap: 50
  chunk_size: 500
  k_retrieval: 5
  system_prompt: You are a helpful research assistant that provides accurate information
    based on the given context. If the answer is not in the context, say you don't
    know.
ui:
  default_provider: OpenAI
  max_history: 10
  theme: default
enhancements:
  content_moderation_model: unitary/toxic-bert
  reranker_model: cross-encoder/ms-marco-MiniLM-L-6-v2
